name: bisect wasm build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2026-06
      - name: Установить wasm-ld
        run: sudo apt-get update && sudo apt-get install -y lld
      - name: Собрать panos.wasm
        run: odin build wasm -target:js_wasm32 -o:size -out:demo/panos.wasm
